-- AlterTable
ALTER TABLE "Location" ADD COLUMN     "gracePeriod" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "code" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "phone" SET DEFAULT '';
